-- AlterTable
ALTER TABLE `billing` ADD COLUMN `periode` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `collaterallending` ADD COLUMN `sub_status` ENUM('PENDING', 'DISETUJUI', 'DITOLAK', 'SELESAI') NOT NULL DEFAULT 'PENDING';
